services:
  frontend:
    build: .
    container_name: ShareMeSomethingFront
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8080
    stdin_open: true
    tty: true